import Head from 'next/head';
import styles from '../styles/Home.module.css';
// import useQuery from urql
import { useQuery } from 'urql';
// improt the query we want to use 
import { PRODUCT_QUERY } from '../lib/query';



export default function Home() {
  // Fetch products from strapi
  const [results] = useQuery({query: PRODUCT_QUERY});
  // console.log the results and get back the data, fetching and errors
  const { data, fetching, error } = results;

  // Check for the data coming in
  if(fetching) return <p>Loading...</p>;
  if(error) return <p>Oh no... {error.message}</p>;
  console.log(data);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Next.js!
        </h1>
      </main>
    </div>
  )
}


