import Head from 'next/head';
// import useQuery from urql
import { useQuery } from 'urql';
// improt the query we want to use 
import { PRODUCT_QUERY } from '../lib/query';
// Components
import Product from '../components/Products';
// Styles
import { Gallery } from '../styles/Gallery';

// Framer-Motion Variants Parent
const cards = {
  hidden: { opacity: 1 },
  show: {
      opacity: 1,
      transition: {
          delayChildren: 0.3,
          staggerChildren: 0.1,
      },
  },
};


export default function Home() {
  // Fetch products from strapi
  const [results] = useQuery({query: PRODUCT_QUERY});
  // console.log the results and get back the data, fetching and errors
  const { data, fetching, error } = results;

  // Check for the data coming in
  if(fetching) return <p>Loading...</p>;
  if(error) return <p>Oh no... {error.message}</p>;
  const products = data.products.data;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Gallery
        variants={cards}
        initial='hidden'
        animate='show'
        >
          {products.map((product) => (
            <Product  
            key={product.attributes.slug} 
            product={product} 
            />
          ))}
        </Gallery>
      </main>
    </div>
  )
}


